[package]
name = "ectf-2024-uiuc-ap"
authors = ["SIGPwny <ctf@sigpwny.com>"]
edition = "2021"
version = "0.1.0"

[dependencies]
argon2 = "0.5.3"
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
